import { ProjectType } from '../enums/project-type.enum';
import { Project } from '../models/project.model';
import { TechnologyName } from '../enums/technology-name.enum';

export const projects: Project[] = [
  {
    id: 'artimon',
    title: 'Artimon',
    type: ProjectType.RESPONSIVE,
    thumbnailImageUrl:
      '/assets/images/projects/artimon/artimon-thumbnail.png',
    shortDescription:
      'Artimon is a decentralised application that lets you generate unique monsters (Artimons) with the help of AI which can then be minted as NFTs.',
    task: 'The challenge was to create a website which makes it possible to bring monsters generated by a machine learning model onto the Ethereum blockchain in the form of NFTs and display all Aritmons with their corresponding owner.',
    result:
      'I built a React dApp which uses a Tensorflow model to generate unique Artimons. Artimons can then be minted as NFTs via the MetaMask wallet. Furthermore the data of all Artimons ever minted is read from the Ethereum blockchain and displayed in the form of the Artidex.',
    slideshowImagesUrls: [
      '/assets/images/projects/artimon/artimon-1.jpg',
      '/assets/images/projects/artimon/artimon-2.jpg',
      '/assets/images/projects/artimon/artimon-3.jpg',
      '/assets/images/projects/artimon/artimon-4.jpg',
      '/assets/images/projects/artimon/artimon-5.jpg',
      '/assets/images/projects/artimon/artimon-6.jpg',
    ],
    technologyNames: [
      TechnologyName.HTML,
      TechnologyName.CSS,
      TechnologyName.SASS,
      TechnologyName.JAVA_SCRIPT,
      TechnologyName.TYPE_SCRIPT,
      TechnologyName.ANGULAR,
      TechnologyName.FIREBASE,
      TechnologyName.PYTHON,
      TechnologyName.PY_TORCH,
    ],
    execution: '',
    accentColor: '#ffffff',
  },
  {
    id: 'thai-rin-ruam',
    title: 'Thai Rin Ruam',
    type: ProjectType.RESPONSIVE,
    thumbnailImageUrl:
      '/assets/images/projects/thai-rin-ruam/thai-rin-ruam-thumbnail.png',
    shortDescription:
      'The website is the digital presence of the renowned Thai restaurant Thai Rin Ruam based in Kevelaer, Germany.',
    task: 'The challenge was to renew their existing website. This primarily included a modern redesign, making the website responsive and the functionality to change the menu and the news section by Thai Rin Ruam themselves at any given time.',
    result:
      'I created a web application with the help of Angular based on a design mockup. The website is divided into two compartments, one for users, one for admins. The former displays information like news, all available dishes, address information etc. The latter is used to provide the functionality for authenticated users to dynamically change dishes and news which enabled Thai Rin Ruam to make changes to the website themselves after project handover.',
    slideshowImagesUrls: [
      '/assets/images/projects/thai-rin-ruam/thai-rin-ruam-1.jpg',
      '/assets/images/projects/thai-rin-ruam/thai-rin-ruam-2.jpg',
      '/assets/images/projects/thai-rin-ruam/thai-rin-ruam-3.jpg',
      '/assets/images/projects/thai-rin-ruam/thai-rin-ruam-4.jpg',
      '/assets/images/projects/thai-rin-ruam/thai-rin-ruam-5.jpg',
      '/assets/images/projects/thai-rin-ruam/thai-rin-ruam-6.jpg',
    ],
    technologyNames: [
      TechnologyName.HTML,
      TechnologyName.CSS,
      TechnologyName.SASS,
      TechnologyName.JAVA_SCRIPT,
      TechnologyName.TYPE_SCRIPT,
      TechnologyName.ANGULAR,
      TechnologyName.FIREBASE,
      TechnologyName.PYTHON,
      TechnologyName.PY_TORCH,
    ],
    execution: '',
    accentColor: '#ffffff',
  },
  {
    id: 'tomke-nils',
    title: 'Tomke Nils',
    type: ProjectType.RESPONSIVE,
    thumbnailImageUrl:
      '/assets/images/projects/tomke-portfolio/tomke-portfolio-thumbnail.png',
    shortDescription:
      'The web application serves as a portfolio for the rising photo-, videographer, social media manager and influencer Tomke Nils.',
    task: 'The challenge was to first come up with a modern and sleek design and then build a responsive website based on that that would display information regarding provided services, recent projects, a live instagram feed etc. After project handover it should be possible to change certain content by Tomke himself.',
    result:
      'A responsive Angular application was created based on a design mockup which encompasses a user and an admin space. The user space shows static information like services, contact information etc. as well as dynamic information like projects and an instagram feed. The dynamic information are controlled via the admin space which is login-locked and provides an easy-to-use interface to create, edit and delete information by Tomke himself.',
    slideshowImagesUrls: [
      '/assets/images/projects/tomke-portfolio/tomke-portfolio-1.jpg',
      '/assets/images/projects/tomke-portfolio/tomke-portfolio-2.jpg',
      '/assets/images/projects/tomke-portfolio/tomke-portfolio-3.jpg',
      '/assets/images/projects/tomke-portfolio/tomke-portfolio-4.jpg',
      '/assets/images/projects/tomke-portfolio/tomke-portfolio-5.jpg',
      '/assets/images/projects/tomke-portfolio/tomke-portfolio-6.jpg',
    ],
    technologyNames: [
      TechnologyName.HTML,
      TechnologyName.CSS,
      TechnologyName.SASS,
      TechnologyName.JAVA_SCRIPT,
      TechnologyName.TYPE_SCRIPT,
      TechnologyName.ANGULAR,
      TechnologyName.FIREBASE,
      TechnologyName.PYTHON,
      TechnologyName.PY_TORCH,
    ],
    execution: '',
    accentColor: '#ffffff',
  },
  {
    id: 'paintable-paws',
    title: 'Paintable Paws',
    type: ProjectType.MOBILE,
    thumbnailImageUrl:
      '/assets/images/projects/paintable-paws/paintable-paws-thumbnail.png',
    shortDescription:
      'Paintable Paws allows you to turn photographs of pets into art using AI, with a variety of different art styles to choose from.',
    task: 'The challenge was to optimise a machine learning model that can turn an arbitrary photo into an artwork with a user-defined style. A web application should then be built to enable users to upload a photograph of their pet and select their preferred style as well as submit their email so that they can receive the artwork once it\'s processed by the AI.',
    result:
      'I optimised a machine learning model so that it can apply any style to any image. Furthermore I assisted in developing the frontend application in Angular and took care of the connection to the backend with the help of Firebase.',
    slideshowImagesUrls: [
      '/assets/images/projects/paintable-paws/paintable-paws-screen-1-1200p.png',
      '/assets/images/projects/paintable-paws/paintable-paws-screen-2-1200p.png',
      '/assets/images/projects/paintable-paws/paintable-paws-screen-3-1200p.png',
      '/assets/images/projects/paintable-paws/paintable-paws-screen-4-1200p.png',
      '/assets/images/projects/paintable-paws/paintable-paws-screen-5-1200p.png',
    ],
    technologyNames: [
      TechnologyName.HTML,
      TechnologyName.CSS,
      TechnologyName.SASS,
      TechnologyName.JAVA_SCRIPT,
      TechnologyName.TYPE_SCRIPT,
      TechnologyName.ANGULAR,
      TechnologyName.FIREBASE,
      TechnologyName.PYTHON,
      TechnologyName.PY_TORCH,
    ],
    execution: '',
    accentColor: '#554A7D',
  },
];
