export enum TechnologyName {
  'ANGULAR' = 'Angular',
  'REACT' = 'React',
  'HTML' = 'HTML5',
  'CSS' = 'CSS3',
  'JAVA_SCRIPT' = 'JavaScript',
  'SASS' = 'Sass',
  'MONGO_DB' = 'MongoDB',
  'MY_SQL' = 'MySQL',
  'PHP' = 'PHP',
  'FIREBASE' = 'Firebase',
  'PYTHON' = 'Python',
  'TYPE_SCRIPT' = 'TypeScript',
  'PY_TORCH' = 'PyTorch',
  'ETHERS' = 'ethers.js',
  'META_MASK' = 'MetaMask',
  'TAILWINDCSS' = 'tailwindcss',
  'IPFS' = 'IPFS',
  'WAGMI' = 'wagmi',
  'NEXT' = 'Next.js',
}
